version: '3'
services:
  db:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - ./.db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
